FROM ubuntu
RUN apt-get update && apt-get install -y wget make
RUN mkdir -p /opt/cross
# RUN wget https://musl.cc/i686-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/i686-linux-musl-cross /opt/cross/i686-unknown-linux-musl && ln -s /opt/cross/i686-unknown-linux-musl/bin/i686-linux-musl-gcc /opt/cross/i686-unknown-linux-musl/bin/i686-unknown-linux-musl-gcc
# RUN wget https://musl.cc/x86_64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/x86_64-linux-musl-cross /opt/cross/x86_64-unknown-linux-musl && ln -s /opt/cross/x86_64-unknown-linux-musl/bin/x86_64-linux-musl-gcc /opt/cross/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc
# RUN wget https://musl.cc/mips-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mips-linux-musl-cross /opt/cross/mips-unknown-linux-musl && ln -s /opt/cross/mips-unknown-linux-musl /opt/cross/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc
# RUN wget https://musl.cc/mipsel-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross &&  ln -s /opt/cross/mipsel-linux-musl-cross /opt/cross/mipsel-unknown-linux-musl
# RUN wget https://musl.cc/mips64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross &&  ln -s /opt/cross/mips64-linux-musl-cross /opt/cross/mips64-unknown-linux-musl 
# RUN wget https://musl.cc/mips64el-linux-musl-cross.tgz -O -  | tar -xz -C /opt/cross &&  ln -s /opt/cross/mips64el-linux-musl-cross /opt/cross/mips64el-unknown-linux-musl 
# RUN wget https://musl.cc/arm-linux-musleabi-cross.tgz -O - | tar -xz -C /opt/cross &&  ln -s /opt/cross/arm-linux-musleabi-cross /opt/cross/arm-unknown-linux-musleabi
# RUN wget https://musl.cc/aarch64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/aarch64-linux-musl-cross /opt/cross/aarch64-unknown-linux-musl 
# RUN wget https://musl.cc/x86_64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/x86_64-linux-musl-cross /opt/cross/x86_64-unknown-linux-musl && ln -s /opt/cross/x86_64-unknown-linux-musl/bin/x86_64-linux-musl-cross-gcc /opt/cross/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc
# RUN wget https://musl.cc/i686-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/i686-linux-musl-cross /opt/cross/i686-unknown-linux-musl && ln -s /opt/cross/i686-unknown-linux-musl/bin/i686-linux-musl-cross-gcc /opt/cross/i686-unknown-linux-musl/bin/i686-unknown-linux-musl-gcc
# RUN wget https://musl.cc/mips-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mips-linux-musl-cross /opt/cross/mips-unknown-linux-musl && ln -s /opt/cross/mips-unknown-linux-musl/bin/mips-linux-musl-cross-gcc /opt/cross/mips-unknown-linux-musl/bin/mips-unknown-linux-musl-gcc
# RUN wget https://musl.cc/mipsel-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mipsel-linux-musl-cross /opt/cross/mipsel-unknown-linux-musl && ln -s /opt/cross/mipsel-unknown-linux-musl/bin/mipsel-linux-musl-cross-gcc /opt/cross/mipsel-unknown-linux-musl/bin/mipsel-unknown-linux-musl-gcc
# RUN wget https://musl.cc/arm-linux-musleabi-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/arm-linux-musleabi-cross /opt/cross/arm-unknown-linux-musleabi && ln -s /opt/cross/arm-unknown-linux-musleabi/bin/arm-linux-musleabi-cross-gcc /opt/cross/arm-unknown-linux-musleabi/bin/arm-unknown-linux-musleabi-gcc
# RUN wget https://musl.cc/aarch64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/aarch64-linux-musl-cross /opt/cross/aarch64-unknown-linux-musl && ln -s /opt/cross/aarch64-unknown-linux-musl/bin/aarch64-linux-musl-cross-gcc /opt/cross/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-gcc
# RUN wget https://musl.cc/mips64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mips64-linux-musl-cross /opt/cross/mips64-unknown-linux-muslabi64 && ln -s /opt/cross/mips64-unknown-linux-muslabi64/bin/mips64-linux-muslabi64-cross-gcc /opt/cross/mips64-unknown-linux-muslabi64/bin/mips64-unknown-linux-muslabi64-gcc
# RUN wget https://musl.cc/mips64el-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mips64el-linux-musl-cross /opt/cross/mips64el-unknown-linux-muslabi64 && ln -s /opt/cross/mips64el-unknown-linux-muslabi64/bin/mips64el-linux-muslabi64-cross-gcc /opt/cross/mips64el-unknown-linux-muslabi64/bin/mips64el-unknown-linux-muslabi64-gcc

RUN wget https://musl.cc/x86_64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/x86_64-linux-musl-cross /opt/cross/x86_64-unknown-linux-musl && ln -s /opt/cross/x86_64-unknown-linux-musl/bin/x86_64-linux-musl-gcc /opt/cross/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc
RUN wget https://musl.cc/i686-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/i686-linux-musl-cross /opt/cross/i686-unknown-linux-musl && ln -s /opt/cross/i686-unknown-linux-musl/bin/i686-linux-musl-gcc /opt/cross/i686-unknown-linux-musl/bin/i686-unknown-linux-musl-gcc
RUN wget https://musl.cc/mips-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mips-linux-musl-cross /opt/cross/mips-unknown-linux-musl && ln -s /opt/cross/mips-unknown-linux-musl/bin/mips-linux-musl-gcc /opt/cross/mips-unknown-linux-musl/bin/mips-unknown-linux-musl-gcc
RUN wget https://musl.cc/mipsel-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mipsel-linux-musl-cross /opt/cross/mipsel-unknown-linux-musl && ln -s /opt/cross/mipsel-unknown-linux-musl/bin/mipsel-linux-musl-gcc /opt/cross/mipsel-unknown-linux-musl/bin/mipsel-unknown-linux-musl-gcc
RUN wget https://musl.cc/arm-linux-musleabi-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/arm-linux-musleabi-cross /opt/cross/arm-unknown-linux-musleabi && ln -s /opt/cross/arm-unknown-linux-musleabi/bin/arm-linux-musleabi-gcc /opt/cross/arm-unknown-linux-musleabi/bin/arm-unknown-linux-musleabi-gcc
RUN wget https://musl.cc/aarch64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/aarch64-linux-musl-cross /opt/cross/aarch64-unknown-linux-musl && ln -s /opt/cross/aarch64-unknown-linux-musl/bin/aarch64-linux-musl-gcc /opt/cross/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-gcc
RUN wget https://musl.cc/mips64-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mips64-linux-musl-cross /opt/cross/mips64-unknown-linux-muslabi64 && ln -s /opt/cross/mips64-unknown-linux-muslabi64/bin/mips64-linux-musl-gcc /opt/cross/mips64-unknown-linux-muslabi64/bin/mips64-unknown-linux-muslabi64-gcc
RUN wget https://musl.cc/mips64el-linux-musl-cross.tgz -O - | tar -xz -C /opt/cross && ln -s /opt/cross/mips64el-linux-musl-cross /opt/cross/mips64el-unknown-linux-muslabi64 && ln -s /opt/cross/mips64el-unknown-linux-muslabi64/bin/mips64el-linux-musl-gcc /opt/cross/mips64el-unknown-linux-muslabi64/bin/mips64el-unknown-linux-muslabi64-gcc