name: Compile and Publish HyperNVRAM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build 
        run: |
          docker run --rm -v $PWD:/app -w /app ghcr.io/panda-re/embedded-toolchains:latest /app/build.sh

      - name: Save package
        uses: actions/upload-artifact@v3
        with:
          name: hypernvram
          path: build